services:
  mysql_service:
    build: ./mysql_database
    image: mysql_service:v1
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3307"  
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -P 3307 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    
  database_api_service:
    build: ./database_api
    image: database_api_service:v1
    container_name: database_api_service
    depends_on:
      mysql_service:
        condition: service_healthy
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      SQL_DATABASE_URL: ${SQL_DATABASE_URL}
    ports:
      - "8002:8002"
    networks:
      - app_network

  data_ingestion_service:
    build: ./data_ingestion
    image: data_ingestion_service:v1
    container_name: data_ingestion_service
    depends_on:
      - database_api_service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_KEY: ${API_KEY}
    ports:
      - "8001:8001"  
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s        
      timeout: 5s          
      retries: 3           
      start_period: 60s 

  front_end_service:
    build: ./front-end/news
    image: front_end_service:v1
    depends_on:
      - database_api_service
    container_name: front_end_service
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3000:3000" 
    networks:
      - app_network
    env_file:
      - .env

  clustering_service:
    build: ./clustering
    image: clustering_service:v1
    container_name: clustering_service
    depends_on:
      - mysql_service
      - database_api_service
      - data_ingestion_service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8005:8005"  
    networks:
      - app_network

  sentiment_analysis_service:
    build: ./sentimental_analysis
    image: sentimental_analysis_service:v1
    container_name: sentimental_analysis_service
    depends_on:
      - mysql_service
      - database_api_service
      - data_ingestion_service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8006:8006"  
    networks:
      - app_network
      
volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge
