"""empty message

Revision ID: 4af4e57df91a
Revises: e121420c7673
Create Date: 2024-11-28 00:19:08.604792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af4e57df91a'
down_revision = 'e121420c7673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clustering_results',
    sa.Column('cluster_name', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('weights', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clustering_results')
    # ### end Alembic commands ###
