"""empty message

Revision ID: 595a3ef886a9
Revises: 4af4e57df91a
Create Date: 2024-11-28 00:19:44.445225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595a3ef886a9'
down_revision = '4af4e57df91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
