"""empty message

Revision ID: e121420c7673
Revises: 
Create Date: 2024-11-28 00:18:48.041473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e121420c7673'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('published_date_precision', sa.String(length=255), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('clean_url', sa.String(length=255), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rights', sa.String(length=255), nullable=True),
    sa.Column('rank_news', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('media', sa.Text(), nullable=True),
    sa.Column('is_opinion', sa.Boolean(), nullable=True),
    sa.Column('twitter_account', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_articles')
    # ### end Alembic commands ###
